// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajfhvksbhrpmjclchrrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqZmh2a3NiaHJwbWpjbGNocnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDM4NjcsImV4cCI6MjA3MDY3OTg2N30.0R56TfUYTDMNx7bCeUpMjOp87k6yri9oOdueoQAhBoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});